// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzqWVP580i7FWt2508SytYB-Jca8z0Z2A',
    appId: '1:534235175908:web:944f19b900de49a6c345f1',
    messagingSenderId: '534235175908',
    projectId: 'todo-8ed01',
    authDomain: 'todo-8ed01.firebaseapp.com',
    storageBucket: 'todo-8ed01.firebasestorage.app',
    measurementId: 'G-2ZSYFY830M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8nETBym_5sVDeB4LT0bTBKuYjEv-sn48',
    appId: '1:534235175908:android:9322f7c58b05ec91c345f1',
    messagingSenderId: '534235175908',
    projectId: 'todo-8ed01',
    storageBucket: 'todo-8ed01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKwWcFPtFJxiVquPU1ULKJoMgf39Dk5Zs',
    appId: '1:534235175908:ios:646ae701728072b1c345f1',
    messagingSenderId: '534235175908',
    projectId: 'todo-8ed01',
    storageBucket: 'todo-8ed01.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKwWcFPtFJxiVquPU1ULKJoMgf39Dk5Zs',
    appId: '1:534235175908:ios:646ae701728072b1c345f1',
    messagingSenderId: '534235175908',
    projectId: 'todo-8ed01',
    storageBucket: 'todo-8ed01.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzqWVP580i7FWt2508SytYB-Jca8z0Z2A',
    appId: '1:534235175908:web:a6fb550161f17737c345f1',
    messagingSenderId: '534235175908',
    projectId: 'todo-8ed01',
    authDomain: 'todo-8ed01.firebaseapp.com',
    storageBucket: 'todo-8ed01.firebasestorage.app',
    measurementId: 'G-EVL0DXCB04',
  );
}
